package co.touchlab.kjwt.hardware.model

/**
 * Controls whether keys generated by the hardware-backed key factories are backed by a
 * dedicated secure hardware element.
 *
 * This preference is interpreted platform-specifically:
 * - **Android:** controls use of StrongBox (a dedicated secure element separate from the default
 *   Trusted Execution Environment). Requires API 28+.
 * - **Apple (iOS/macOS):** controls use of the Secure Enclave for ES256 (P-256) keys. Keys stored
 *   in the Secure Enclave never leave the secure element even during signing operations.
 */
public enum class SecureHardwarePreference {
    /**
     * Do not request dedicated secure-hardware key storage. Default behaviour.
     *
     * On Android, keys are generated in the default TEE-backed Keystore. On Apple platforms,
     * keys are stored in the standard Keychain bound to the device via
     * `kSecAttrAccessibleAfterFirstUnlock`, with signing performed on the main CPU.
     */
    None,

    /**
     * Use secure hardware when available, falling back silently to the default storage otherwise.
     *
     * On Android, StrongBox is used when the device supports it (API 28+); otherwise the default
     * TEE-backed Keystore is used. On Apple platforms, the Secure Enclave is used when the
     * algorithm supports it (ES256/P-256 only); all other algorithms fall back to the standard
     * Keychain silently.
     */
    Preferred,

    /**
     * Require dedicated secure-hardware key storage; throw if unavailable.
     *
     * On Android, throws [IllegalStateException] if the device is below API 28 or has no
     * StrongBox. On Apple platforms, throws [IllegalArgumentException] if the requested algorithm
     * does not support the Secure Enclave (i.e., any algorithm other than ES256).
     */
    Required,
}
